# Numpy

In [1]:
import numpy as np

In [2]:
# Generating a one-dimension array (vector)

lst = [0,1,2,3,4,5,6,7]
v=np.array(lst)
print(v)
print(v.shape)
#v is a vector, a one-column array. Its shape has only 1 number.
b = v.reshape(1,8)
print(b)
print(b.shape)

[0 1 2 3 4 5 6 7]
(8,)
[[0 1 2 3 4 5 6 7]]
(1, 8)


In [3]:
# Generating a 2-dimension array (matrix)

lst_lsts = [[0,1,2,3],[4,5,6,7]]
m=np.array((lst_lsts))
print(m)

[[0 1 2 3]
 [4 5 6 7]]


In [4]:
tup_lsts = ([0,1,2,3],[4,5,6,7])
a=np.array((tup_lsts))
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [5]:
tup_tups = ((1,2,3,4,5),(10,9,8,7,6))
M = np.array((tup_tups))
print(M)

[[ 1  2  3  4  5]
 [10  9  8  7  6]]


In [6]:
lst_tups = [(1,2,3,4,5),(10,9,8,7,6),(0,1,0,1,0)]
A = np.array((lst_tups))
print(A)

[[ 1  2  3  4  5]
 [10  9  8  7  6]
 [ 0  1  0  1  0]]


In [7]:
#  Navigating a 2-dimensional array
print(A[0])

[1 2 3 4 5]


In [8]:
#  Navigating a 2-dimensional array
print(A[0:2])

[[ 1  2  3  4  5]
 [10  9  8  7  6]]


In [9]:
#  Navigating a 2-dimensional array
print(A[0,2])

3


In [10]:
#  Navigating a 2-dimensional array
print(A[:,2:4])

[[3 4]
 [8 7]
 [0 1]]


In [11]:
#  Navigating a 2-dimensional array
print(A[:2,2:4])

[[3 4]
 [8 7]]


In [12]:
#  Navigating a 2-dimensional array
print(A[1:3,0:3])

[[10  9  8]
 [ 0  1  0]]


In [13]:
# Generating a 3-dimension array (tensor) with random numbers
t = np.random.random((3,2,4))
# ou
t = np.random.randn(3,2,4)
# ou
t = np.random.randint(1000,size=(3,2,4))
# ou
t = np.empty([3,2,4])
print(t)

[[[ 0.1848735   0.03321506 -1.78203081 -0.08265353]
  [-0.20969977 -1.53112204  2.26025529 -0.04393107]]

 [[-0.52608684  1.3222538   0.02273596  0.54927984]
  [-1.35506867 -1.31515177  0.82130016  0.610916  ]]

 [[-0.45897601  0.04529506 -0.49034446  0.07102277]
  [ 1.11559076 -0.33282304 -0.98768611  0.9408022 ]]]


In [14]:
#  Navigating a 3-dimensional array
print(t[0])
print(t[0,1,:2])
print(t[1:3,0,2:4])

[[ 0.1848735   0.03321506 -1.78203081 -0.08265353]
 [-0.20969977 -1.53112204  2.26025529 -0.04393107]]
[-0.20969977 -1.53112204]
[[ 0.02273596  0.54927984]
 [-0.49034446  0.07102277]]


In [15]:
# Operations within an array
# Suppose a 3-dimensional array with integers
c = np.random.randint(10,size=(2,4))
print(c)

[[4 0 3 3]
 [5 8 5 7]]


In [16]:
    # Sums within an array:
# You can sum along the axes of the array
# The axis i in np.sum(array, axis=i) is the ith index of the shape of that array (zero-indexed).   

print(np.sum(c, axis=0)), print()
# sum of each column in matrix c

print(np.sum(c, axis=1))
# sum of each row in matrix c:

[ 9  8  8 10]

[10 25]


In [17]:
# Other sums within the array:
print(np.sum(c[0])),print()
print(np.sum(c[:,1]))

10

8


In [18]:
    # de même, pour la moyenne arithmétique :
print(np.mean(c[:,1:3]))
print(np.mean(c, axis = 0))

4.0
[4.5 4.  4.  5. ]


In [19]:
print(np.median(c, axis = 0))
print(np.min(c, axis = 0))
print(np.max(c, axis = 0))
print(np.std(c, axis = 0))

[4.5 4.  4.  5. ]
[4 0 3 3]
[5 8 5 7]
[0.5 4.  1.  2. ]


In [20]:
# Operations between separate arrays

In [21]:
print("c[0]","\n", c[0]), print()
print("c[1]","\n", c[1])

c[0] 
 [4 0 3 3]

c[1] 
 [5 8 5 7]


In [22]:
x = np.add(c[0],c[1])
x

array([ 9,  8,  8, 10])

In [23]:
np.subtract(c[0],c[1])

array([-1, -8, -2, -4])

In [24]:
np.multiply(c[0],c[1])

array([20,  0, 15, 21])

In [25]:
np.divide(c[0],c[1])

array([0.8       , 0.        , 0.6       , 0.42857143])

In [26]:
np.divide(c[0],c[1])

array([0.8       , 0.        , 0.6       , 0.42857143])