In [1]:
def add_(x, y):
    return x + y

In [2]:
add_(3, 4)

7

In [3]:
" ".join(['a', 'b', 'c'])

'a b c'

In [4]:
class Dog:
    #constructeur
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def description(self):
        return f'{self.name} is {self.age} years old'
    
    def speak(self, sound):
        return f'{self.name} says {sound}!'

In [5]:
jackrussel = Dog('bill', 3)

In [6]:
jackrussel.name

'bill'

In [7]:
jackrussel.age

3

In [8]:
jackrussel.description()

'bill is 3 years old'

In [9]:
jackrussel.speak('woof')

'bill says woof!'

In [10]:
a = Dog('bill', 3)
b = Dog('bill', 3)

In [11]:
a == b

False

In [12]:
l = ['a', 'b', 'c']

In [13]:
' '.join(l)

'a b c'

In [14]:
class Comparaisons:
    def min(a, b):
        if a < b:
            return a
        else:
            return b

In [15]:
Comparaisons.min(2, 3) # méthode statique

2

In [16]:
class JackRussel(Dog):
    def hunt(self, prey):
        return f'{self.name} hunts {prey}'
    
    def speak(self):
        return super().speak('Arf')

In [17]:
SpottedJackRussel = JackRussel('Medor', 10)

In [18]:
SpottedJackRussel.description()

'Medor is 10 years old'

In [19]:
SpottedJackRussel.speak()

'Medor says Arf!'

In [20]:
# Error JackRussel.hunt('sheep')

In [21]:
SpottedJackRussel.hunt('sheep')

'Medor hunts sheep'

In [22]:
SpottedJackRussel = JackRussel('Roxy', 5)

In [23]:
SpottedJackRussel.description()

'Roxy is 5 years old'

In [24]:
cocker = Dog('boule', 4)

In [25]:
cocker.description()

'boule is 4 years old'

In [26]:
# ERROR cocker.hunt('sheep')

In [27]:
isinstance('bill', Dog)

False

In [28]:
isinstance(jackrussel, Dog)

True

In [29]:
isinstance(cocker, JackRussel)

False

In [30]:
class LinearReg:
    #constructeur
    def __init__(self, fit_intercept=True):
        self.fit_intercept = fit_intercept
        self.coefficients = None
        self.intercept = None
        
    def fit(self, X, y):
        # This function returns the fitted linear model 
        # input: X - predictor variables and y - response variables
        # output: regression coefficients
        
        xtx = np.dot(X.T, X) ## x-transpose times x
        xtx_inv = np.linalg.inv(xtx) ## inverse of x-transpose times x
        xty = np.dot(X.T, y) ## x-transpose times y
        coefficients = np.dot(xtx_inv, xty)
        print(coefficients)
        
        if self.fit_intercept:
            self.intercept = coefficients[0]
            self.coefficients = coefficients[1:]
        else:
            self.intercept = 0
            self.coefficients = coefficients
            
            
    def predict(self, X):
        # This function returns the predicted values
        # input: array of dependent variables
        # output: predicted values
        if len(X.shape) == 1:
            X = X.reshape(-1,1)
            return self.intercept + np.dot(X, self.coefficients) 

In [31]:
linreg = LinearReg(fit_intercept=False)

In [32]:
import numpy as np

In [33]:
X_train = np.array([40, 60, 35, 100])
y_train = np.array([400000, 650000, 300000, 1100000])

In [34]:
y_train

array([ 400000,  650000,  300000, 1100000])

In [35]:
linreg.fit(X_train.reshape(-1, 1), y_train)

[10684.93150685]


In [36]:
X_train.reshape(-1, 1)

array([[ 40],
       [ 60],
       [ 35],
       [100]])

In [37]:
X_train

array([ 40,  60,  35, 100])

In [38]:
X_test = np.array([20, 50, 200])

In [39]:
for p in linreg.predict(X_test):
    print(f'{p} euros')

213698.6301369863 euros
534246.5753424657 euros
2136986.3013698626 euros


In [40]:
len(X_test.reshape(-1, 1).shape)

2

## Katas

### Kata "Remove All The Marked Elements of a List"
Define a method/function that removes from a given array of integers all the values contained in a second array.

Example:
- integer_list =  [1, 1, 2 ,3 ,1 ,2 ,3 ,4]
- values_list = [1, 3]
- l.remove_(integer_list, values_list) == [2, 2, 4]

In [13]:
def remove_(integer_list, values_list):
        blacklist = set(values_list)
        return [val for val in integer_list if val not in blacklist]
int =  [1, 1, 2 ,3 ,1 ,2 ,3 ,4]
val = [1, 3] 
remove_(int,val)

[2, 2, 4]

### Kata "Method For Counting Total Occurence Of Specific Digits"
We need a method in the List Class that may count specific digits from a given list of integers. The method wiltl output a list of tuples, each tuple having two elements, the first one will be a digit to count, and second one, its corresponding total frequency in all the integers of the first list. This list of tuples should be ordered with the same order that the digits have in digitsList.

Example:
- intlist = [-18, -31, 81, -19, 111, -888]
- digitlist = [1, 8, 4]
- l.count_spec_digits(intlist, digitlist) == [(1, 7), (8, 5), (4, 0)]

In [19]:
intlist = [1, 11, 32, 333, 43]
digitlist = [1, 2, 3]

In [20]:
''.join([str(1), str(11), str(32)]).count(str(1))

3

In [21]:
result1 = [(x, ''.join([str(y) for y in intlist]).count(str(x))) for x in digitlist]
print(result1)

[(1, 3), (2, 1), (3, 5)]


In [28]:
result2 = [(x,y) for x,y in zip(digitlist,([int(y) for x in intlist for y in str(x).count(i) for i in set(digitlist)]))]

print(result2)

UnboundLocalError: local variable 'i' referenced before assignment

### Kata "Ordered Count of Characters"
Count the number of occurrences of each character in a string and return it as a list of tuples in order of appearance. For empty output return an empty list.

Example: 
ordered_count("abracadabra") == [('a', 5), ('b', 2)

In [7]:
from sortedcontainers import SortedSet
def ordered_count(inp):
    return [(x,inp.count(x)) for x in SortedSet(inp)]
ordered_count("abracadabra")

[('a', 5), ('b', 2), ('c', 1), ('d', 1), ('r', 2)]